### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lch88** [fivetran/dbt_apple_store#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Building `apple_store__subscription_report` model fails with following error on BigQuery.

```
21:44:25  Completed with 1 error and 0 warnings:
21:44:25  
21:44:25  Database Error in model apple_store__subscription_report (models/apple_store__subscription_report.sql)
21:44:25    No matching signature for operator = for argument types: DATE, STRING. Supported signature: ANY = ANY at [243:12]
21:44:25    compiled Code at target/run/apple_store/models/apple_store__subscription_report.sql
21:44:25  
21:44:25  Done. PASS=27 WARN=0 ERROR=1 SKIP=1 TOTAL=29
```

The code referred here seems to be:
https://github.com/fivetran/dbt_apple_store/blob/0e7ea500f5303c95afb0da395502ee5b81f6c9f5/models/apple_store__subscription_report.sql#L88

### Relevant error log or model output

```shell
Error log itself is provided above.
```

### Expected behavior

It should run without any issue.

### dbt Project configurations

I have set the `using_subscriptions` flag to true.

```
vars:
  # set source database and schema name (https://github.com/fivetran/dbt_app_reporting#step-3-configure-database-and-schema-variables)
  apple_store_database: project-XXX
  apple_store_schema: itunes_connect
  google_play_database: project-XXX
  google_play_schema: google_play

  # enable subscriptions and earnings models (https://github.com/fivetran/dbt_app_reporting#step-4-disable-and-enable-source-tables)
  apple_store__using_subscriptions: true # by default this is assumed to be false
  google_play__using_subscriptions: true # by default this is assumed to be false
  google_play__using_earnings: true # by default this is assumed to be false
```

### Package versions

packages:
  - package: fivetran/app_reporting
    version: 0.2.0

### What database are you using dbt with?

bigquery

### dbt Version

Core:
  - installed: 1.4.1
  - latest:    1.4.1 - Up to date!

Plugins:
  - bigquery: 1.4.0 - Up to date!

### Additional Context

As a temporary measure, I changed the line to 
```
reporting_grain.date_day = cast(subscription_events.date_day as date)
```
and it worked.

Maybe it would be better if it is fixed in other location like upstream model.

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
